

name: Push to Heroku

on: push

jobs:
  test: # runs on every push
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2.1.5
      - name: Installing dependencies
        run: npm run install
      - name: Building static files
        run: npm run build
  
  production:
    runs-on: ubuntu-latest
    if: success() && github.ref == 'refs/heads/master'
    steps:
      - uses: akhileshns/heroku-deploy@v3.12.12 # This is the action
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "woc-au"
          heroku_email: ${{secrets.HEROKU_EMAIL}}
